//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baza2
{
    using System;
    using System.Collections.Generic;
    
    public partial class czlowiekSet_bibliotekarz
    {
        public int IdB { get; set; }
        public string stazPracy { get; set; }
        public int Id { get; set; }
        public int wypozyczenie_Id { get; set; }
    
        public virtual czlowiekSet czlowiekSet { get; set; }
        public virtual wypozyczenieSet wypozyczenieSet { get; set; }
    }
}
