//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baza2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<czlowiekSet> czlowiekSet { get; set; }
        public virtual DbSet<czlowiekSet_bibliotekarz> czlowiekSet_bibliotekarz { get; set; }
        public virtual DbSet<czlowiekSet_czytelnik> czlowiekSet_czytelnik { get; set; }
        public virtual DbSet<ksiazkaSet> ksiazkaSet { get; set; }
        public virtual DbSet<wypozyczenieSet> wypozyczenieSet { get; set; }
    }
}
