//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baza2
{
    using System;
    using System.Collections.Generic;
    
    public partial class wypozyczenieSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wypozyczenieSet()
        {
            this.czlowiekSet_bibliotekarz = new HashSet<czlowiekSet_bibliotekarz>();
        }
    
        public int Id { get; set; }
        public System.DateTime dataWypozyczenia { get; set; }
        public System.DateTime dataZwrotu { get; set; }
        public int ksiazka_Id { get; set; }
        public int czytelnik_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<czlowiekSet_bibliotekarz> czlowiekSet_bibliotekarz { get; set; }
        public virtual czlowiekSet_czytelnik czlowiekSet_czytelnik { get; set; }
        public virtual ksiazkaSet ksiazkaSet { get; set; }
    }
}
